### PR TITLE
Neil/201 docs folder

### PR DESCRIPTION
**Pull request by neilZon**
# Description
This Pr adds a github action and docs folder to allow the new docsite to render `.md` and `.mdx` from this repo

related: onflow/next-docs-v1#201

### CODE REVIEW

**Review by psiemens — COMMENTED** [review]
Is `overview.md` just a copy of `README.md`? Unfortunately that's not a scalable solution -- the two files are bound to get out of sync.

Did y'all consider any workarounds to this? Would symlinking work? Could the docs site build be configured with a special case for README files?

**Review by psiemens — APPROVED** [review]
Approving and merging for now, but let's make sure we circle back with a better solution for this.

**Comment by sideninja** [comment]
@psiemens I remember discussing this exact point with @hanaito0 and I believe she had some ideas on how to possibly make that as part of GHA. Can't find the thread now tho, but I agree, that duplicating content like that should be avoided at all costs.

**Comment by sideninja** [comment]
Also now thinking about it, we could just remove the README in root folder and have the source of truth in docs folder, but named as README, since github anyhow checks that as per https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes#about-readmes

**Pull request merged**
